---
title: "Conditional plots"
author: "Bernd Panassiti"
date: 'created: 07.06.2023, last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```




# Loading of packages and data
```{r loading_data, include=FALSE}
#Install/load pacman
if(!require(pacman)){install.packages("pacman");require(pacman)}
#Install packages
p_load(tidyverse,magrittr,caret,ggplot2,DHARMa,broom.mixed,
       posterior,ggdist,tidybayes,pryr,bayesplot,ggpubr,grid,gridExtra,
       emmeans,broom, broom.mixed,
       posterior,brms,bayesplot,ggpubr,
       hrbrthemes,patchwork,# additional themes
       GGally) # ggpairs

source("r-code/00_functions.R")

load("results/modelResults.RData")
```


# Conditional effect plot
## Insect model - Management predictors

```{r}
# Output the conditional effects.
fit.TD = modelResultsTDManagement[[1]]
fit.PD = modelResultsPDManagement[[1]]
fit.FD = modelResultsFDManagement[[1]]

ce<- conditional_effects(fit.TD,"grazingTime")
plot(ce, plot = FALSE)[[1]] +
  labs(x= "Grazing times",y="Wild bee TD")+
  theme_light()+mytheme

# cond_mat.PD <- conditional_effects(fit.PD,"grazingTime:surveyPeriod")[[1]] 
# cond_mat.PD$type = rep("PD",nrow(cond_mat.PD))
# cond_mat.PD %<>% rename(estimate = "estimate__",se="se__",lowCI = "lower__", highCI = "upper__")
# cond_mat.PD %<>% dplyr::select(type,grazingTime,surveyPeriod,estimate,se,lowCI,highCI)
# 
# cond_mat.FD <- conditional_effects(fit.FD,"grazingTime:surveyPeriod")[[1]] 
# cond_mat.FD$type = rep("FD",nrow(cond_mat.FD))
# cond_mat.FD %<>% rename(estimate = "estimate__",se="se__",lowCI = "lower__", highCI = "upper__")
# cond_mat.FD %<>% dplyr::select(type,grazingTime,surveyPeriod,estimate,se,lowCI,highCI)
```








## Insect model - Vegetation predictors -Bees
```{r}
#bee
fit = modelResultsTDVegetation[[1]]

ce=conditional_effects(fit,"nInflorescenceCoocc")
beePlot_TD_flower = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Number of Inflorescences",y="Wild bee TD")+
  theme_light()+mytheme


ce=conditional_effects(fit,"nPlantSpecies")
beePlot_TD_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Wildbee TD")+
  theme_light()+mytheme

ce=conditional_effects(fit,"coverHerbs")
beePlot_TD_cover = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant cover",y="Wildbee TD")+
  theme_light()+mytheme

# PD
fit = modelResultsPDVegetation[[1]]

ce=conditional_effects(fit,"nInflorescenceCoocc")
beePlot_PD_flower = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Number of Inflorescences",y="Wild bee PD")+
  theme_light()+mytheme


ce=conditional_effects(fit,"nPlantSpecies")
beePlot_PD_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Wildbee PD")+
  theme_light()+mytheme

ce=conditional_effects(fit,"coverHerbs")
beePlot_PD_cover = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant cover",y="Wildbee PD")+
  theme_light()+mytheme


# PD
fit = modelResultsFDVegetation[[1]]

ce=conditional_effects(fit,"nInflorescenceCoocc")
beePlot_FD_flower = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Number of Inflorescences",y="Wild bee FD")+
  theme_light()+mytheme


ce=conditional_effects(fit,"nPlantSpecies")
beePlot_FD_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Wildbee FD")+
  theme_light()+mytheme

ce=conditional_effects(fit,"coverHerbs")
beePlot_FD_cover = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant cover",y="Wildbee FD")+
  theme_light()+mytheme

ggpubr::ggarrange(beePlot_TD_SR, beePlot_TD_flower,beePlot_TD_cover, 
                  beePlot_PD_SR, beePlot_PD_flower,beePlot_PD_cover,
                  beePlot_FD_SR, beePlot_FD_flower,beePlot_FD_cover,
                  ncol=3,nrow=3)
```

## Insect model - Vegetation predictors -Bees
```{r}
#bee
fit.TD = modelResultsTDVegetation[[1]]

ce=conditional_effects(fit.TD,"nInflorescenceCoocc")

beePlot_flower = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Number of Inflorescences",y="Wild bee TD")+
  theme_light()+mytheme


fit.TD = modelResultsTDVegetation[[1]]

ce=conditional_effects(fit.TD,"nPlantSpecies")

beePlot_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Wildbee TD")+
  theme_light()+mytheme

# butterfly
fit.TD = modelResultsTDVegetation[[2]]

ce=conditional_effects(fit.TD,"nInflorescenceCoocc")

butterflyPlot_flower = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Number of Inflorescences",y="Butterfly TD")+
  theme_light()+mytheme


ce=conditional_effects(fit.TD,"nPlantSpecies")

butterflyPlot_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Butterfly TD")+
  theme_light()+mytheme

# planthopper 1
fit.TD = modelResultsTDVegetation[[3]]

ce=conditional_effects(fit.TD,"nPlantSpecies")

planthopperPlot_SR = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Plant species richness",y="Planthopper TD")+
  theme_light()+mytheme

# planthopper 2
fit.TD = modelResultsTDVegetation[[4]]

ce=conditional_effects(fit.TD,"height")

planthopperPlot_height = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Vegetation height",y="Planthopper TD")+
  theme_light()+mytheme

ce=conditional_effects(fit.TD,"biomass")

planthopperPlot_biomass = plot(ce, plot = FALSE)[[1]] +
  labs(x= "Biomass",y="Planthopper TD")+
  theme_light()+mytheme



ggpubr::ggarrange(beePlot_SR, beePlot_flower, 
                  butterflyPlot_SR,butterflyPlot_flower,
                  planthopperPlot_SR, planthopperPlot_height,
                  planthopperPlot_biomass,
                  ncol=4,nrow=2)
```

